# [Reachy2 from Pollen Robotics](https://www.pollen-robotics.com)

# Requires installing extras packages
# With pip: `pip install -e ".[reachy2]"`
# With poetry: `poetry install --sync --extras "reachy2"`


_target_: lerobot.common.robot_devices.robots.reachy2.ReachyRobot

robot_type: Reachy2

cameras:
  head_left:
    _target_: lerobot.common.robot_devices.robots.reachy2.Reachycamera
    name: teleop
    host: localhost
    port: 50065
    image_type: left
  head_right:
    _target_: lerobot.common.robot_devices.robots.reachy2.Reachycamera
    name: teleop
    host: localhost
    port: 50065
    image_type: right
  torso_rgb:
    _target_: lerobot.common.robot_devices.robots.reachy2.Reachycamera
    name: depth
    host: localhost
    port: 50065
    image_type: rgb
  torso_depth:
    _target_: lerobot.common.robot_devices.robots.reachy2.Reachycamera
    name: depth
    host: localhost
    port: 50065
    image_type: depth
