# @package _global_

fps: 50

env:
  name: aloha
  task: AlohaInsertion-v0
  from_pixels: True
  pixels_only: False
  image_size: [3, 480, 640]
  episode_length: 500
  fps: ${fps}
  state_dim: 6
  action_dim: 6
