# @package _global_

fps: 30

env:
  name: dora
  task: DoraAloha-v0
  # from_pixels: True
  # pixels_only: False
  # image_size: [3, 480, 640]
  episode_length: 400
  # fps: ${fps}
  # state_dim: 14
  # action_dim: 14
